#!/usr/bin/env bash
# Starts the VibeSet dev stack: Fastify API on :4317 + Vite UI on :5173.
#
# WHY THIS SCRIPT EXISTS
# ----------------------
# The machine's default `node` is v14, far too old for the Salesforce libraries
# (Node >= 22) and for corepack's own shims. Every corepack shim starts with
# `#!/usr/bin/env node`, so running a bare `pnpm` picks up whatever node PATH
# resolves first — under v14 that dies immediately with:
#
#     process.env.COREPACK_ENABLE_DOWNLOAD_PROMPT??='1'
#                                                ^^^
#     SyntaxError: Unexpected token '??='
#
# Prepending Node 22 to PATH is necessary but NOT sufficient: Turbo spawns
# `pnpm` itself for each package's script, and any caller that resets or
# reorders PATH reintroduces the bug. So we also drop a real `pnpm` shim into
# ./.dev-bin that hardcodes the Node 22 binary, and put that first on PATH.
# That makes every downstream `pnpm` node-version-safe by construction.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# --- 1. Resolve a Node >= 22 -------------------------------------------------
NODE_BIN=""
if [ -f .nvmrc ]; then
  WANTED="$(tr -d 'v \t\n' < .nvmrc)"
  for candidate in "$HOME/.nvm/versions/node/v${WANTED}"*/bin; do
    [ -x "$candidate/node" ] && NODE_BIN="$candidate" && break
  done
fi
if [ -z "$NODE_BIN" ]; then
  for candidate in $(ls -d "$HOME"/.nvm/versions/node/v*/bin 2>/dev/null | sort -V -r); do
    major="$("$candidate/node" -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
    if [ "$major" -ge 22 ] 2>/dev/null; then NODE_BIN="$candidate"; break; fi
  done
fi
if [ -z "$NODE_BIN" ]; then
  echo "error: no Node >= 22 found under ~/.nvm. VibeSet requires Node 22+." >&2
  exit 1
fi
NODE="$NODE_BIN/node"

# --- 2. Resolve pnpm's real entry point, bypassing the corepack shim ---------
PNPM_VERSION="$("$NODE" -p "require('$REPO_ROOT/package.json').packageManager.split('@')[1]" 2>/dev/null || echo '')"
PNPM_CJS=""
for cand in \
  "$HOME/.cache/node/corepack/v1/pnpm/${PNPM_VERSION}/bin/pnpm.cjs" \
  "$HOME/.cache/node/corepack/pnpm/${PNPM_VERSION}/bin/pnpm.cjs"; do
  [ -f "$cand" ] && PNPM_CJS="$cand" && break
done
if [ -z "$PNPM_CJS" ]; then
  # Not provisioned yet — let corepack fetch it once, under Node 22.
  export PATH="$NODE_BIN:$PATH"
  export COREPACK_INTEGRITY_KEYS=0 COREPACK_ENABLE_DOWNLOAD_PROMPT=0
  "$NODE" "$NODE_BIN/../lib/node_modules/corepack/dist/corepack.js" prepare --activate >/dev/null 2>&1 || true
  for cand in "$HOME/.cache/node/corepack/v1/pnpm/${PNPM_VERSION}/bin/pnpm.cjs"; do
    [ -f "$cand" ] && PNPM_CJS="$cand" && break
  done
fi
if [ -z "$PNPM_CJS" ]; then
  echo "error: could not locate pnpm ${PNPM_VERSION}. Run: corepack prepare --activate" >&2
  exit 1
fi

# --- 3. Build a node-version-safe `pnpm` shim and put it first on PATH -------
SHIM_DIR="$REPO_ROOT/.dev-bin"
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/pnpm" <<EOF
#!/bin/sh
# Generated by scripts/dev.sh — pins pnpm to Node 22 so Turbo's child
# invocations cannot fall back to the system Node 14. Do not edit by hand.
exec "$NODE" "$PNPM_CJS" "\$@"
EOF
chmod +x "$SHIM_DIR/pnpm"

export PATH="$SHIM_DIR:$NODE_BIN:$PATH"
export COREPACK_INTEGRITY_KEYS=0
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0

echo "▸ node $("$NODE" -v)  ($NODE_BIN)"
echo "▸ pnpm $("$SHIM_DIR/pnpm" -v)  (shimmed)"

# --- 4. Dev session token ----------------------------------------------------
# The API mints a random token per boot and embeds it in its own launch URL.
# In dev the UI is served by Vite on :5173 and never sees that URL, so pin the
# token to a known value and append it to the browser URL instead.
# NOTE: these must also be declared in turbo.json `globalEnv`, or Turbo's
# strict env mode silently drops them before they reach the server process.
export VIBESET_TOKEN="${VIBESET_TOKEN:-dev-local-token}"
export VIBESET_PORT="${VIBESET_PORT:-4317}"

echo "▸ API  http://127.0.0.1:${VIBESET_PORT}"
echo "▸ UI   http://127.0.0.1:5173/?token=${VIBESET_TOKEN}"
echo

exec "$SHIM_DIR/pnpm" run dev
